package co.edu.javeriana.isml.generator.test

import co.edu.javeriana.isml.generator.common.SimpleTemplate
import org.eclipse.emf.ecore.EObject

import static org.junit.Assert.*

// Probar con EntityGenerator
class TestGeneratorHelper {

	/**
	 * Verifies whether a templates generates the expected output code from a given input model element. Both the 
	 * generated code and the expected output code strings are processed to remove excess whitespaces and to
	 * add spaces both before and after any non alphabetic character. This should facilitate comparison between expected output
	 * and generated code, since the programmer does not have to worry about whitespaces.
	 * To force a 1-to-1 comparison, utilize the method {@link TestGeneratorHelper#assertGeneratesVerbatim}
	 * @param template The template
	 * @param input The input model element. This element is fed to the template to generate code
	 * @param expectedOutput The expected code to be generated by the template
	 */
	def <T extends EObject> void assertGenerates(SimpleTemplate<T> template, T input, CharSequence expectedOutput) {
		val generatedText = template.toText(input)
		val trimmedGeneratedText = generatedText.trimUnwantedChars
		val trimmedExpectedOutput = expectedOutput.trimUnwantedChars
		compare(trimmedGeneratedText, trimmedExpectedOutput, expectedOutput)
	}

	/**
	 * Verifies whether a templates generates the expected output code from a given input model element. The expected
	 * output must be <b>exactly</b> the same as the generated code, otherwise the assertion fails.
	 * @param template The template
	 * @param input The input model element. This element is fed to the template to generate code
	 * @param expectedOutput The expected code to be generated by the template
	 */
	def <T extends EObject> void assertGeneratesVerbatim(SimpleTemplate<T> template, T input, CharSequence expectedOutput) {
		val generatedText = template.toText(input)
		val trimmedGeneratedText = generatedText.trimUnwantedChars
		val trimmedExpectedOutput = expectedOutput.trimUnwantedChars
		compare(trimmedGeneratedText, trimmedExpectedOutput, expectedOutput)
	}

	def compare(String trimmedGeneratedText, String trimmedExpectedOutput, CharSequence expectedOutput) {
		if (!trimmedGeneratedText.equals(trimmedExpectedOutput)) {
			printCallingMethod()
			println("\nExpected output:\n\"" + trimmedExpectedOutput + "\"")
			println("Generated code: \n\"" + trimmedGeneratedText + "\"")
			fail("Incorrect generated text. Expected: \n" + expectedOutput + "\n\nbut got:\n" + trimmedGeneratedText)
		}
	}

	def printCallingMethod() {
		println(Thread.currentThread.stackTrace.get(2).methodName)
	}

	def trimUnwantedChars(CharSequence seq) {
		return String.valueOf(seq)//				.replaceAll("[,;|\\.\\*\\+\\-/]", " $0 ")
//				.replaceAll("[\\(\\)\\{\\}\\[\\]<>]", " $0 ")
		.replaceAll("[^A-Za-z]", " $0 ").replaceAll("\\s+", " ").trim

	}

}