/*
 * generated by Xtext
 */
package co.edu.javeriana.isml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import com.google.inject.Module;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IsmlUiModule extends co.edu.javeriana.isml.ui.AbstractIsmlUiModule implements Module {
	public IsmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
